name: Java CI

on: 
  push: 
    branches: master
    tags: v*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy -Dregistry=https://maven.pkg.github.com/maxiko -Dtoken=521dc2a5ffcb615c92f5a0a74f1b9f37c0e1b494

    - name: Static Code Anaylizis
      run: mvn -B clean sonar:sonar
